# Generated by Django 5.2.6 on 2026-03-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status_alter_orderevent_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='abandoned_cart_reminder_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
