# Generated by Django 5.2.6 on 2026-03-08 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_orders_orde_user_id_37fed6_idx_and_more'),
        ('products', '0005_product_products_pr_is_acti_defdf1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_user_id_37fed6_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'payment_status', 'created_at'], name='orders_orde_user_id_0e54be_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_item_per_order_product'),
        ),
    ]
