# Generated by Django 5.2.6 on 2026-03-07 14:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('stock_limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='products.product')),
            ],
            options={
                'ordering': ('start_time', '-created_at'),
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='products_fl_start_t_8bd860_idx'), models.Index(fields=['product'], name='products_fl_product_82a2c7_idx')],
            },
        ),
    ]
