# Generated by Django 5.2.6 on 2026-03-07 16:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0011_cart_abandoned_cart_reminder_sent_at'),
        ('products', '0003_flashsale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('business_name',),
            },
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('earnings_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='orders.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='vendors.vendor')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_listing', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='vendors.vendor')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['user'], name='vendors_ven_user_id_d902b7_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['slug'], name='vendors_ven_slug_6ed865_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active'], name='vendors_ven_is_acti_5c8a37_idx'),
        ),
        migrations.AddIndex(
            model_name='vendororder',
            index=models.Index(fields=['vendor'], name='vendors_ven_vendor__83ff2f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendororder',
            index=models.Index(fields=['order'], name='vendors_ven_order_i_41ec54_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendororder',
            constraint=models.UniqueConstraint(fields=('vendor', 'order'), name='unique_vendor_order'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['vendor'], name='vendors_ven_vendor__2148c7_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['product'], name='vendors_ven_product_493669_idx'),
        ),
    ]
