# Generated by Django 5.2.6 on 2026-03-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_orders_orde_user_id_37fed6_idx_and_more'),
        ('products', '0005_product_products_pr_is_acti_defdf1_idx_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendororder',
            index=models.Index(fields=['vendor', 'created_at'], name='vendors_ven_vendor__b0c47b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['vendor', 'created_at'], name='vendors_ven_vendor__16a68f_idx'),
        ),
    ]
