# Generated by Django 5.2.6 on 2026-03-02 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('razorpay_order_id', models.CharField(max_length=255, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255)),
                ('amount', models.PositiveBigIntegerField(help_text='Amount in paise')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'captured')), fields=('order',), name='unique_captured_payment_per_order')],
            },
        ),
    ]
