# Generated by Django 5.2.6 on 2026-03-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentevent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.CheckConstraint(condition=models.Q(('id__isnull', False)), name='prevent_update'),
        ),
    ]
