# Generated by Django 5.2.6 on 2026-03-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentevent_immutable_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('verified', 'Verified'), ('failed', 'Failed'), ('duplicate', 'Duplicate'), ('refunded', 'Refunded'), ('replay', 'Replay'), ('retry_attempt', 'Retry Attempt'), ('payment_failed', 'Payment Failed'), ('payment_success', 'Payment Success')], max_length=30),
        ),
    ]
