# Generated by Django 5.2.6 on 2026-03-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_orders_orde_user_id_37fed6_idx_and_more'),
        ('payments', '0005_alter_paymentevent_event_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'),
        ),
    ]
