# Generated by Django 5.2.6 on 2026-03-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_referral_owner_code_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('vendor', 'Vendor')], default='student', max_length=20),
        ),
    ]
